name: SpeedyTools
version: '${project.version}'
main: me.lagggpixel.speedytools.Main
api-version: 1.20
commands:
  speedytools:
    aliases:
      - speedytool
    permission: speedytools.command
    description: Speedy Tools
permissions:
  speedytools.use.tools:
    default: true
  speedytools.use.armor:
    default: true
  speedytools.use.swords:
    default: true
  speedytools.command:
    default: false